[build]
  publish = "."
  command = "npm install && npm run build"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[build.environment]
  NODE_VERSION = "18"

# Enable Netlify Identity for CMS authentication
[template.environment]
  NETLIFY_CMS_MANUAL_INIT = "true"
